version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalog:
    image: events/eventcatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=EventCatalogDb;User ID=sa;Password=Eventcatalog(2$);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false"
      ExternalBaseUrl: http://localhost:5000
    ports:
      - "5000:80"
    container_name: eventscatalog
    networks:
      - frontend
      - backend
    depends_on: 
      - mssqlserver
 
  eventstokenserver:
    image: events/tokenapi
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=tokensqlserver;Initial Catalog=TokenServiceDb;User ID=sa;Password=Eventcatalog(2$);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false"
      MvcClient: http://localhost:7080
    ports:
      - "5020:80"
    container_name: eventstokenapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokensqlserver





  webmvcnew:
    image: events/webmvcnew
    build:
      context: .\WebMVCnew
      dockerfile: Dockerfile
    environment: 
      ASPNETCORE_ENVIRONMENT: Production
      EventCatalogUrl: http://eventcatalog
      IdentityUrl: http://192.168.1.15:5020
      CallBackUrl: http://localhost:7080
    ports:
      - "7080:80"
    container_name: eventsticketsshop
    networks:
      - frontend
    depends_on:
      - eventcatalog
      - eventstokenserver
     
  

  mssqlserver:
     image: "mcr.microsoft.com/mssql/server:latest"
     environment:
       ACCEPT_EULA: Y
       MSSQL_SA_PASSWORD: Eventcatalog(2$)
       SA_PASSWORD: Eventcatalog(2$)
     ports:
       - "5001:1433"
     container_name: eventssqlserver
     networks:
       - backend

  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
       ACCEPT_EULA: Y
       MSSQL_SA_PASSWORD: Eventcatalog(2$)
       SA_PASSWORD: Eventcatalog(2$)
    ports:
      - "5010:1433"
    container_name: eventstokensqlserver
    networks:
      - backend